"""
Base strategy class that defines the interface for all trading strategies.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from datetime import datetime
import pandas as pd
import numpy as np
from dataclasses import dataclass

@dataclass
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.
    
    Attributes:
        symbol: The stock symbol this signal is for
        strategy: The name of the strategy that generated this signal
        action: The recommended action ('BUY', 'SELL', or 'HOLD')
        probabilities: Dictionary mapping actions to their probabilities
        confidence: Confidence level of the signal (0.0 to 1.0)
        timestamp: When the signal was generated
        features: Features used to generate the signal
    """
    symbol: str
    action: str  # 'BUY', 'SELL', or 'HOLD'
    probabilities: Dict[str, float]  # e.g., {'BUY': 0.7, 'SELL': 0.2, 'HOLD': 0.1}
    confidence: float  # 0.0 to 1.0
    timestamp: datetime  # Timestamp of the signal
    features: Dict[str, float]  # Features used to generate the signal

class BaseStrategy(ABC):
    """Base class for all trading strategies."""
    
    def __init__(self, name: str):
        """Initialize base strategy.
        
        Args:
            name: Name of the strategy
        """
        self.name = name
        
    @abstractmethod
    def train_model(self, data: pd.DataFrame, symbol: str) -> None:
        """Prepare data for the strategy.
        
        Args:
            data: Raw price/indicator data
            symbol: Stock symbol
            
        Returns:
            Processed data ready for strategy
        """
        pass
        
    @abstractmethod
    def generate_signals(
        self,
        features: Dict[str, float],
        symbol: str,
        timestamp: datetime
    ) -> StrategySignal:
        """Generate trading signals for a symbol at a given timestamp.
        
        Args:
            features: Dictionary of features for the current timestamp
            symbol: Stock symbol
            timestamp: Current timestamp
            
        Returns:
            StrategySignal with probabilities and confidence
        """
        pass
        
    @abstractmethod
    def update(self, data: pd.DataFrame, symbol: str) -> None:
        """Update strategy with new data.
        
        Args:
            data: New data to update the strategy with
            symbol: Stock symbol
        """
        pass
        
    def get_features(self) -> List[str]:
        """Get list of features used by the strategy.
        
        Returns:
            List of feature names
        """
        return []
        
    def get_parameters(self) -> Dict[str, Any]:
        """Get strategy parameters.
        
        Returns:
            Dictionary of strategy parameters
        """
        return {}
        
    def set_parameters(self, parameters: Dict[str, Any]) -> None:
        """Set strategy parameters.
        
        Args:
            parameters: Dictionary of strategy parameters
        """
        pass 